server:
  port: 8095

spring:
  application:
    name: msvc-contability
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/erpdb
    username: postgres
    password: curso

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:8762/eureka
