server:
  port: 8087

spring:
  application:
    name: msvc-login
  datasource:
    url: jdbc:mysql://localhost:3307/erpdb
    username: root
    password: curso
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret:
    key: 2zzSWKEwFPJmjJvXjvg03xqmwewO5hHFKZBTuDkpkoU=
  time:
    expiration: 86400000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:8762/eureka